import type { Metadata } from "next";
import "./globals.css";
import local from "next/font/local";

const font = local({ src: "../../public/fonts/san-francisco-reg.woff2"})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${font.className}`}>{children}</body>
    </html>
  );
}
