-- MySQL Script generated by MySQL Workbench
-- Sun Jan 21 12:44:34 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Usuarios` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Usuarios` (
  `id` INT NOT NULL DEFAULT 0,
  `NIF` VARCHAR(9) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NULL,
  `email` VARCHAR(254) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`NIF`),
  UNIQUE INDEX `NIF_UNIQUE` (`NIF` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Device`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Device` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Device` (
  `id` INT NOT NULL,
  `Latitud` FLOAT NULL,
  `Longitud` FLOAT NULL,
  `Battery` INT NOT NULL,
  `Cpu_temp` INT NOT NULL,
  `Usuario` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `device_user_fk`
    FOREIGN KEY (`Usuario`)
    REFERENCES `mydb`.`Usuarios` (`NIF`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cpu_temps`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Cpu_temps` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Cpu_temps` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `device` INT NOT NULL,
  `value` INT NOT NULL,
  `time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  INDEX `id_device_fk_idx` (`device` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `id_device_fk0`
    FOREIGN KEY (`device`)
    REFERENCES `mydb`.`Device` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
